version: '3.7'
services:

  natal-admin:
    container_name: natal-admin
    env_file:
      - .env
    restart: always
    build:
      context: ./admin
    environment:
      - VITE_FB_API_KEY=${VITE_FB_API_KEY}
      - VITE_FB_AUTH_DOMAIN=${VITE_FB_AUTH_DOMAIN}
      - VITE_FB_PROJECT_ID=${VITE_FB_PROJECT_ID}
      - VITE_FB_STORAGE_BUCKET=${VITE_FB_STORAGE_BUCKET}
      - VITE_FB_MESSAGING_SENDER_ID=${VITE_FB_MESSAGING_SENDER_ID}
      - VITE_FB_APP_ID=${VITE_FB_APP_ID}
    volumes:
      - ./admin:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - net-natal

  natal-client:
    container_name: natal-client
    env_file:
      - .env
    restart: always
    build:
      context: ./client
    environment:
      - VITE_FB_API_KEY=${VITE_FB_API_KEY}
      - VITE_FB_AUTH_DOMAIN=${VITE_FB_AUTH_DOMAIN}
      - VITE_FB_PROJECT_ID=${VITE_FB_PROJECT_ID}
      - VITE_FB_STORAGE_BUCKET=${VITE_FB_STORAGE_BUCKET}
      - VITE_FB_MESSAGING_SENDER_ID=${VITE_FB_MESSAGING_SENDER_ID}
      - VITE_FB_APP_ID=${VITE_FB_APP_ID}
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - net-natal

networks:
  net-natal: